'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

function collectJs(dir, output = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) collectJs(full, output);
    else if (entry.name.endsWith('.js')) output.push(full);
  }
  return output;
}

test('native renderer integrates local music, media, MV, Discord and updates into the new UI', () => {
  const native = read('public/js/shinayuu-v2-native.js');
  for (const feature of [
    'openLocalLibrary',
    'openMediaLibrary',
    'shinayuu-mv-background',
    'openDiscordSettings',
    'checkUpdate',
  ]) assert.ok(native.includes(feature), `missing native renderer feature ${feature}`);
  assert.match(native, /setCustomBackgroundMedia/);
  assert.match(native, /youtube-video\/song\/video/);
  assert.match(native, /updateDiscordActivity/);
  assert.match(native, /setTimeout\([^\n]*1800|1800/);
});

test('playlist shelf keeps virtualization and disables expensive full-panel live blur', () => {
  const state = read('public/js/modules/00-state/01-perf-render-state.js');
  const css = read('public/css/index.css');
  assert.match(state, /PLAYLIST_LAZY_BATCH_SIZE\s*=\s*36/);
  assert.match(state, /QUEUE_VIRTUAL_OVERSCAN\s*=\s*3/);
  assert.match(state, /PLAYLIST_CARD_VIRTUAL_OVERSCAN_PX\s*=\s*260/);
  assert.match(state, /PLAYLIST_DETAIL_VIRTUAL_OVERSCAN\s*=\s*4/);
  assert.match(css, /ShinaYuu Music 2\.0: playlist shelf scroll performance guard/);
  assert.match(css, /#playlist-panel,[\s\S]*?backdrop-filter:\s*none\s*!important/);
  assert.match(css, /content-visibility:\s*auto/);
  assert.match(css, /overscroll-behavior:\s*contain/);
});

test('renderer bundle contains the modular visual UI and official version', () => {
  const bundle = read('public/js/shinayuu-index-bundle.js');
  const html = read('public/index.html');
  assert.match(bundle, /Generated by tools\/build-renderer-bundle\.js/);
  assert.match(bundle, /14-stage-lyrics-rendering\.js/);
  assert.match(bundle, /03-wallpaper-engine-library\.js/);
  assert.match(bundle, /currentVersion:\s*'2\.0\.15'/);
  assert.match(html, /shinayuu-index-bundle\.js\?v=2\.0\.15/);
  assert.match(html, /shinayuu-v2-native\.js\?v=2\.0\.15/);
});

test('all application JavaScript parses successfully', () => {
  const files = [
    ...collectJs(path.join(root, 'desktop')),
    ...collectJs(path.join(root, 'public', 'js')),
    ...collectJs(path.join(root, 'tools')),
    ...collectJs(path.join(root, 'scripts')),
    path.join(root, 'server.js'),
    path.join(root, 'music-providers.js'),
    path.join(root, 'local-library.js'),
    path.join(root, 'kugou-api.js'),
    path.join(root, 'qishui-api.js'),
    path.join(root, 'youtube-caption-provider.js'),
    path.join(root, 'youtube-forced-aligner.js'),
  ];
  for (const file of files) {
    const result = spawnSync(process.execPath, ['--check', file], { encoding: 'utf8' });
    assert.equal(result.status, 0, `${path.relative(root, file)}\n${result.stderr || result.stdout}`);
  }
});
